---
title: "Criando um gráfico no ggplot2"
author: "Fernando Corrêa"
date: "April 12, 2017"
---

[câmera em F]

Olá! É muito bom te ver novamente. Na aula de hoje vamos aprender o básico para construir gráficos usando o pacote ggplot2. Essa discussão começa descobrindo o que é um gráfico estatístico.

Seguindo as ideias propostas por hadley wickham e leland wilkinson, vamos pensar que um gráfico é uma relação entre três elementos. Entender essa forma de pensar é o fundamento para entender ggplot: o pacote só transforma esse esquema em um código de computador.

O primeiro elemento consiste nas informações de uma bases de dados

[mostra uma tabela 6x4 em LaTex com duas colunas numéricas e duas colunas qualitativas]

como as suas variáveis,

[aparece um retângulo vermelho ao redor das duas primeiras variáveis]

e resumos dos seus dados, como médias e medianas.

[aparece uma seta saindo da última coluna da tabela apontando pra média da última coluna]

O segundo elemento consiste nos parâmetros estéticos do gráfico,

[troca slide. esse slide tem um gráfico em que o x e o y são as colunas numéricas e as cores e os formatos são as colunas qualitativas] como eixos, cores e formatos.

O terceiro e último elemento são anotações finais [novo slide adicionando pedaços ao gráfico anterior], com títulos, legendas e formas geométricas.

Deixando a teoria de lado, podemos aprender como esses conceitos se aplicam no Resqueleto do gráfico é construído através de uma chamada da função ggplot2. os parâmetros são

- a base de dados
- o mapemento com a função aes

as anotações são somadas depois.
    


